# -*- coding: utf-8 -*-
"""Embudo_Robot_AGOSTO_Dia_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5-12lLeTlOGlV8KiRTazlDKdx8kyAq0

## Configuración
"""

import pandas as pd
import pandas_gbq
import numpy as np
from datetime import datetime, date
import warnings
import os
import glob
from google.colab import auth
from google.auth import default
from google.cloud import bigquery
from google.oauth2 import service_account

auth.authenticate_user()
project_id = "capable-arbor-209819"
client = bigquery.Client(project=project_id)

credentials, project = default()

from google.colab import drive
drive.mount('/content/drive')

np.random.seed(42)

# ===========================================================================
# CONSTANTES GLOBALES
# ===========================================================================

TIPIFICACIONES_ROBOT = ["CV_CONT_RECP", "CV_CONT_FILTRO", "102", "103", "CV_RESPONDE_POSITIVO", "CV_CUELGA", "CV_CONT_EQUCV_CONT_EQU"]

GRUPOS_OPERADOR = {
    "DIGITAL": ["DIGITAL_2", "DIGITAL_MONTOS_BAJOS", "DIGITAL_1", "DIGITAL_ESPECIAL"],
    "RBK": ["QNT_RBK_2", "QNT_RBK_1.2", "QNT_RBK_1.1"],
    "MONTOS_ALTOS": ["QNT_RECAUDO", "QNT_PERSONA_JURIDICA", "QNT_JUD"],
    "SATELITES": ["GENNIALS_BPO_2", "GENNIALS_BPO", "HELLO_BPO", "MAPNOVA", "ESTA_BIEN_GROUP", "QNT_COBRO"],
}

BQ_PROJECT_ID = "capable-arbor-209819"
TABLE_EMBUDO = "Operacion_Analitica.Embudo_Positivo_Robot"
TABLE_EMBUDO_MENSUAL = "Operacion_Analitica.Embudo_Positivo_Robot_Mensual"

# ===========================================================================
# FUNCIONES DE LOGGING
# ===========================================================================

def _log(message: str, level: str = "INFO"):
    """Imprime logs con formato consistente."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] [{level}] {message}")

# ===========================================================================
# FUNCIONES DE CLASIFICACIÓN
# ===========================================================================

def classify_operador_grupo(operado_por: str) -> str:
    """Clasifica un operador en su grupo según reglas de negocio."""
    if not operado_por:
        return "OTRO"

    operado_por = str(operado_por).strip().upper()

    if "MANT" in operado_por:
        return "MANTENIMIENTO"

    for grupo, operadores in GRUPOS_OPERADOR.items():
        if operado_por in [op.upper() for op in operadores]:
            return grupo

    return "OTRO"

# ===========================================================================
# OBTENCIÓN DE DATOS DE REFERENCIA DESDE BIGQUERY
# ===========================================================================

def _fetch_reference_data(client, fecha_dia: str) -> dict:
    """
    Obtiene datos de referencia desde BigQuery necesarios para
    las validaciones y cruces del script original.
    """
    ref = {
        "operadores": {},
        "contactos_identificados": set(),
        "gestiones_humanas": {},
        "ventas": {},  # 🔥 DICCIONARIO CON CLAVE (contacto, fecha)
    }

    # 1. Operadores desde Campanas.Campanas_intradia
    try:
        query = """
            SELECT DISTINCT Contacto__c, Operado_Por__c, Name 
            FROM Campanas.Campanas_intradia
        """
        for row in client.query(query).result():
            contacto = str(row.get("Contacto__c", "")).strip()
            if contacto:
                ref["operadores"][contacto] = {
                    "Operado_Por__c": str(row.get("Operado_Por__c", "")),
                    "Name": str(row.get("Name", "")),
                }
        _log(f"Operadores cargados: {len(ref['operadores'])}")
    except Exception as exc:
        _log(f"Error cargando operadores: {exc}", level="WARN")

    # 2. Contactos identificados (GestionesTitular)
    try:
        query = f"""
            SELECT DISTINCT Contacto__c
            FROM Operacion_Analitica.GestionesTitular
            WHERE Fecha_dia >= "{fecha_dia}"
        """
        for row in client.query(query).result():
            contacto = str(row.get("Contacto__c", "")).strip()
            if contacto:
                ref["contactos_identificados"].add(contacto)
        _log(f"Contactos identificados: {len(ref['contactos_identificados'])}")
    except Exception as exc:
        _log(f"Error cargando contactos: {exc}", level="WARN")

    # 3. Gestiones humanas (SalesForce)
    try:
        query = f"""
            SELECT DISTINCT Contacto__c, 
                   SUBSTR(CAST(Fecha_Gestion__c AS STRING), 1, 10) AS Fecha_dia
            FROM SalesForce.Gestion_Oportunidad__c
            WHERE Fecha_Gestion__c >= "{fecha_dia}"
        """
        for row in client.query(query).result():
            contacto = str(row.get("Contacto__c", "")).strip()
            fecha = str(row.get("Fecha_dia", "")).strip()
            if contacto:
                ref["gestiones_humanas"][contacto] = fecha
        _log(f"Gestiones humanas: {len(ref['gestiones_humanas'])}")
    except Exception as exc:
        _log(f"Error cargando gestiones: {exc}", level="WARN")

    # 4. Ventas - 🔥 AHORA CON CLAVE COMPUESTA (contacto, fecha)
    try:
        query = f"""
            SELECT 
                ID_ContactoSalesforce AS Contacto__c, 
                DATE(acu_FechaAcuerdoDePago) AS Fecha_dia
            FROM MySql.qnt_AcuerdoPago
            WHERE acu_FechaAcuerdoDePago >= "{fecha_dia}"
            GROUP BY Contacto__c, Fecha_dia
        """
        for row in client.query(query).result():
            contacto = str(row.get("Contacto__c", "")).strip()
            fecha = str(row.get("Fecha_dia", "")).strip()
            if contacto and fecha:
                # 🔥 Clave compuesta (contacto, fecha)
                ref["ventas"][(contacto, fecha)] = 1
        _log(f"Ventas cargadas: {len(ref['ventas'])}")
    except Exception as exc:
        _log(f"Error cargando ventas: {exc}", level="WARN")

    return ref

# ===========================================================================
# TRANSFORMACIÓN PRINCIPAL
# ===========================================================================

def transform_cdr_to_temp_table(
    cdr_rows: list[dict],
    campaign,
    log,
) -> list[dict]:
    """
    Transforma los datos del CDR al formato de Temporal.Robots_Temporal.
    Aplica todas las reglas de negocio del script de Colab original.
    """
    if not cdr_rows:
        _log("No hay filas CDR para transformar", level="WARN")
        return []

    server_name = (campaign.server_name or "").strip()
    end_dt = log.end_time or datetime.utcnow()
    fecha_dia = end_dt.strftime("%Y-%m-%d")

    # Paso 1: Normalizar columnas del CDR
    normalized_rows = normalize_cdr_columns(cdr_rows, server_name)
    if not normalized_rows:
        _log("No hay filas después de normalizar", level="WARN")
        return []

    # Paso 2: Obtener datos de referencia de BigQuery
    client = get_bigquery_client()
    if client is None:
        _log("Cliente BigQuery no disponible", level="ERROR")
        return []

    ref = _fetch_reference_data(client, fecha_dia)

    # Paso 3: Transformar cada fila
    transformed = []
    processed_customers = set()

    for row in normalized_rows:
        customer_id = str(row.get("CUSTOMER_ID", "")).strip()
        if not customer_id:
            continue

        # 🔥 Obtener la fecha del marcador (día en que el robot contactó)
        fecha_row = str(row.get("DATE", ""))[:10]
        if not fecha_row:
            fecha_row = fecha_dia

        cod_act_raw = row.get("COD_ACT", "")
        cod_act_str = str(cod_act_raw).strip()
        try:
            cod_act_int = int(cod_act_raw) if cod_act_raw not in (None, "") else None
        except (ValueError, TypeError):
            cod_act_int = None

        # Datos del operador desde Campanas_intradia
        operador_info = ref["operadores"].get(customer_id, {})
        operado_por = operador_info.get("Operado_Por__c", "")
        grupo_operador = classify_operador_grupo(operado_por)

        # Determinar si es contacto identificado por robot
        es_contacto_robot = 1 if (
            cod_act_str in TIPIFICACIONES_ROBOT or
            cod_act_int in TIPIFICACIONES_ROBOT
        ) else 0

        # Determinar gestión humana (solo si fue identificado por robot)
        tiene_gestion_humana = customer_id in ref["gestiones_humanas"]
        gestion_humano = 1 if (es_contacto_robot == 1 and tiene_gestion_humana) else 0

        # Determinar contacto identificado humano
        tiene_contacto_humano = customer_id in ref["contactos_identificados"]
        contacto_identificado_humano = 1 if (es_contacto_robot == 1 and tiene_contacto_humano) else 0

        # 🔥 CAMBIO CLAVE: Verificar venta por (contacto, fecha) - IGUAL QUE EL COLAB
        venta_humano_identificado = 1 if (customer_id, fecha_row) in ref["ventas"] else 0

        # Último contacto y localizado histórico
        ultimo_contacto = ""
        localizado_historico = "NO_LOCALIZADO"

        if tiene_gestion_humana:
            ultimo_contacto = ref["gestiones_humanas"].get(customer_id, "")
            if ultimo_contacto:
                try:
                    fecha_gestion = date.fromisoformat(ultimo_contacto[:10])
                    fecha_actual = date.fromisoformat(fecha_row) if fecha_row else end_dt.date()
                    meses_diff = (
                        (fecha_actual.year - fecha_gestion.year) * 12 +
                        (fecha_actual.month - fecha_gestion.month)
                    )
                    localizado_historico = "LOCALIZADO" if meses_diff <= 6 else "PERDIDO"
                except Exception:
                    localizado_historico = "PERDIDO"

        entidad_principal = operador_info.get("Name", "")
        gestion_marcador = 0

        # Construir fila para Temporal.Robots_Temporal
        transformed_row = {
            "Fecha_dia": fecha_dia,
            "DATE": row.get("DATE", ""),
            "TELEPHONE": str(row.get("TELEPHONE", "")),
            "COD_ACT": cod_act_raw,
            "Grupo_Operador": grupo_operador,
            "Operado_Por__c": operado_por,
            "CONN_ID": str(row.get("CONN_ID", "")),
            "Contacto__c": customer_id,
            "Contacto_Identificado_Robot": es_contacto_robot,
            "Gestion_Humano": gestion_humano,
            "Contacto_Identificado_Humano": contacto_identificado_humano,
            "Venta_Humano_Identificado": venta_humano_identificado,
            "Ultimo_Contacto": ultimo_contacto,
            "Entidad_principal": entidad_principal,
            "localizado_historico": localizado_historico,
            "Gestion_Marcador": gestion_marcador,
            "servidor": server_name,
            "campaign_id": campaign.id,
            "execution_id": log.id,
        }

        transformed.append(transformed_row)

    _log(f"Filas transformadas: {len(transformed)}")
    if transformed:
        _log(f"Muestra primera fila: {dict(list(transformed[0].items())[:10])}")

    return transformed

# ===========================================================================
# FUNCIÓN DE NORMALIZACIÓN DE CDR
# ===========================================================================

def normalize_cdr_columns(cdr_rows: list[dict], server_name: str) -> list[dict]:
    """Normaliza las columnas del CDR para que coincidan con el script original."""
    normalized = []
    
    column_mapping = {
        "CUSTOMER_ID": "CUSTOMER_ID",
        "COD_ACT": "COD_ACT",
        "CONN_ID": "CONN_ID",
        "TELEPHONE": "TELEPHONE",
        "DATE": "DATE",
        "TIME_SEC": "TIME_SEC",
        "AGENT_NAME": "AGENT_NAME",
    }
    
    for row in cdr_rows:
        norm_row = {}
        for key, value in row.items():
            key_upper = str(key).strip().upper()
            if key_upper in column_mapping.values():
                norm_row[key_upper] = value
        
        # Asegurar que todas las columnas existan
        for col in column_mapping.values():
            if col not in norm_row:
                norm_row[col] = ""
        
        # Agregar metadata
        norm_row["SERVIDOR"] = server_name
        
        normalized.append(norm_row)
    
    return normalized

# ===========================================================================
# CLIENTE BIGQUERY
# ===========================================================================

def get_bigquery_client():
    """Obtiene el cliente de BigQuery."""
    try:
        return client
    except Exception as exc:
        _log(f"Error obteniendo cliente BigQuery: {exc}", level="ERROR")
        return None

# ===========================================================================
# CARGA A BIGQUERY
# ===========================================================================

def upload_to_temp_table(rows: list[dict]) -> dict:
    """
    Sube los datos transformados a Temporal.Robots_Temporal.
    Borra los datos del día actual antes de insertar (como hace el script original).
    """
    if not rows:
        return {
            "success": False,
            "message": "No hay datos para subir",
            "rows_uploaded": 0,
        }

    client = get_bigquery_client()
    if client is None:
        return {
            "success": False,
            "message": "Cliente BigQuery no disponible",
            "rows_uploaded": 0,
        }

    try:
        fecha_dia = rows[0].get("Fecha_dia", "")
        
        # 1. Borrar datos del día actual
        if fecha_dia:
            delete_query = f"""
                DELETE FROM {TABLE_EMBUDO}
                WHERE Fecha_dia = "{fecha_dia}"
            """
            _log(f"Borrando datos del día {fecha_dia}...")
            job = client.query(delete_query)
            job.result()
            _log("Datos anteriores borrados")

        # 2. Insertar nuevos datos
        _log(f"Insertando {len(rows)} registros en {TABLE_EMBUDO}...")

        df = pd.DataFrame(rows)

        columnas_tabla = [
            "Fecha_dia", "DATE", "TELEPHONE", "COD_ACT", "Grupo_Operador",
            "Operado_Por__c", "CONN_ID", "Contacto__c", "Contacto_Identificado_Robot",
            "Gestion_Humano", "Contacto_Identificado_Humano", "Venta_Humano_Identificado",
            "Ultimo_Contacto", "Entidad_principal", "localizado_historico", "Gestion_Marcador",
        ]

        for col in columnas_tabla:
            if col not in df.columns:
                df[col] = ""

        df_to_upload = df[columnas_tabla]

        pandas_gbq.to_gbq(
            df_to_upload,
            TABLE_EMBUDO,
            project_id=BQ_PROJECT_ID,
            if_exists="append",
            credentials=client._credentials,
        )

        _log(f"✅ {len(df_to_upload)} registros subidos a {TABLE_EMBUDO}")

        return {
            "success": True,
            "message": f"{len(df_to_upload)} registros subidos",
            "rows_uploaded": len(df_to_upload),
        }

    except Exception as exc:
        _log(f"❌ Error subiendo a BigQuery: {exc}", level="ERROR")
        import traceback
        _log(traceback.format_exc(), level="ERROR")
        return {
            "success": False,
            "message": str(exc),
            "rows_uploaded": 0,
        }

# ===========================================================================
# FUNCIÓN PRINCIPAL - ORQUESTADOR
# ===========================================================================

def process_cdr_to_bigquery(campaign, log) -> dict:
    """
    Orquestador completo:
    1. Obtiene CDR desde API de Wolkvox
    2. Normaliza columnas
    3. Transforma datos con reglas de negocio
    4. Sube a Temporal.Robots_Temporal
    
    Returns:
        dict con success, message, rows_uploaded
    """
    _log("=" * 60)
    _log("INICIANDO PROCESAMIENTO CDR → BIGQUERY")
    _log(f"  Campaña: {campaign.name}")
    _log(f"  Servidor: {campaign.server_name}")
    _log(f"  Tabla destino: {TABLE_EMBUDO}")
    _log("=" * 60)

    # Paso 1: Obtener CDR
    _log("Paso 1/4: Obteniendo CDR desde Wolkvox...")
    cdr_rows = fetch_cdr_from_wolkvox(campaign, log)

    if not cdr_rows:
        _log("❌ No se pudo obtener CDR", level="ERROR")
        return {
            "success": False,
            "message": "No se pudo obtener CDR de Wolkvox",
            "rows_uploaded": 0,
        }

    _log(f"  CDR obtenido: {len(cdr_rows)} registros")

    # Paso 2: Normalizar columnas
    _log("Paso 2/4: Normalizando columnas...")
    server_name = (campaign.server_name or "").strip()
    normalized_rows = normalize_cdr_columns(cdr_rows, server_name)
    _log(f"  Filas normalizadas: {len(normalized_rows)}")

    # Paso 3: Transformar datos
    _log("Paso 3/4: Transformando datos con reglas de negocio...")
    transformed_rows = transform_cdr_to_temp_table(normalized_rows, campaign, log)
    _log(f"  Filas transformadas: {len(transformed_rows)}")

    if not transformed_rows:
        _log("❌ No hay datos después de la transformación", level="WARN")
        return {
            "success": False,
            "message": "No hay datos después de la transformación",
            "rows_uploaded": 0,
        }

    # Paso 4: Subir a BigQuery
    _log("Paso 4/4: Subiendo a BigQuery...")
    result = upload_to_temp_table(transformed_rows)

    _log("=" * 60)
    if result.get("success"):
        _log(f"✅ PROCESAMIENTO COMPLETADO: {result.get('rows_uploaded')} registros en {TABLE_EMBUDO}")
    else:
        _log(f"❌ ERROR: {result.get('message')}", level="ERROR")
    _log("=" * 60)

    return result

# ===========================================================================
# FUNCIÓN DE EJECUCIÓN PRINCIPAL
# ===========================================================================

def ejecutar_embudo(dia_actualizacion: list):
    """Ejecuta el embudo completo para un día específico."""
    
    path = f"/content/drive/Shareddrives/Analitica/Embudo de Conversión/Proyecto Robot Omnicanal/Producción/2026-08/Resultados/2026-08/{dia_actualizacion[0]}"
    
    # Listar archivos Excel
    files = [f for f in os.listdir(path) if f.lower().endswith(".xlsx")]
    
    lista_bases = []
    for i in files:
        full_path = os.path.join(path, i)
        df_i = pd.read_excel(full_path, header=0)
        df_i.columns = [i.upper() for i in df_i.columns]
        df_i = df_i[df_i['AGENT_NAME'] != 'TOTAL']
        df_i['SERVIDOR'] = i
        print(full_path, str(df_i.shape[0]))
        lista_bases.append(df_i)
    
    dia_actual = "2026-08-01"
    df_resultados_marcador = pd.concat(lista_bases)
    df_resultados_marcador = df_resultados_marcador[df_resultados_marcador['DATE'].astype(str).str.slice(0,10).isin(dia_actualizacion)].copy().drop_duplicates()
    
    # Leer datos de referencia
    query = """
        SELECT DISTINCT Contacto__c, Operado_Por__c, Name FROM Campanas.Campanas_intradia
    """
    df_operador = pd.read_gbq(query, credentials=credentials, project_id=project_id)
    
    query = f"""
        SELECT DISTINCT Contacto__c, Fecha_dia, 1 AS Contacto_Identificado_Humano
        FROM `Operacion_Analitica.GestionesTitular`
        WHERE Fecha_dia >= "{dia_actual}"
    """
    df_contacto = pd.read_gbq(query, credentials=credentials, project_id=project_id)
    df_contacto['Fecha_dia'] = df_contacto['Fecha_dia'].astype(str)
    
    query = f"""
        SELECT DISTINCT Contacto__c, SUBSTR(CAST(Fecha_Gestion__c AS STRING), 1, 10) Fecha_dia, 1 AS Gestion_Humano
        FROM `SalesForce.Gestion_Oportunidad__c`
        WHERE Fecha_Gestion__c >= "{dia_actual}"
    """
    df_gestion = pd.read_gbq(query, credentials=credentials, project_id=project_id)
    df_gestion['Fecha_dia'] = df_gestion['Fecha_dia'].astype(str)
    
    query = f"""
        SELECT ID_ContactoSalesforce AS Contacto__c, DATE(acu_FechaAcuerdoDePago) AS Fecha_dia, 1 AS Venta_Humano,
        SUM(acu_VrCuota1) acu_VrCuota1, SUM(acu_VrCuotaMensual) acu_VrCuotaMensual,
        SUM(acu_ValorPagadoFiltrado) acu_ValorPagadoFiltrado
        FROM MySql.qnt_AcuerdoPago
        WHERE acu_FechaAcuerdoDePago >= "{dia_actual}"
        GROUP BY Contacto__c, Fecha_dia;
    """
    df_venta = pd.read_gbq(query, credentials=credentials, project_id=project_id)
    df_venta['Fecha_dia'] = df_venta['Fecha_dia'].astype(str)
    
    # Transformar datos - 🔥 AQUÍ SE HACE EL LEFT JOIN POR (CONTACTO, FECHA)
    df_resultados2 = pd.merge(df_resultados_marcador, df_operador, left_on='CUSTOMER_ID', right_on="Contacto__c")
    df_resultados2['Fecha_dia'] = df_resultados2['DATE'].astype(str).str.slice(0,10)
    df_resultados3 = pd.merge(df_resultados2, df_contacto, left_on=['Contacto__c', 'Fecha_dia'], right_on=['Contacto__c', 'Fecha_dia'], how='left')
    df_resultados4 = pd.merge(df_resultados3, df_gestion, left_on=['Contacto__c', 'Fecha_dia'], right_on=['Contacto__c', 'Fecha_dia'], how='left')
    df_resultados5 = pd.merge(df_resultados4, df_venta, left_on=['Contacto__c', 'Fecha_dia'], right_on=['Contacto__c', 'Fecha_dia'], how='left')
    
    # Calcular métricas
    df_resultados5['Contacto_Identificado_Robot'] = np.where(df_resultados5['COD_ACT'].isin(TIPIFICACIONES_ROBOT), 1, 0)
    df_resultados5['Gestion_Humano'] = np.where((df_resultados5['Contacto_Identificado_Robot'] == 1) & (df_resultados5['Gestion_Humano'].fillna(0) == 1), 1, 0)
    df_resultados5['Contacto_Identificado_Humano'] = np.where((df_resultados5['Contacto_Identificado_Robot'] == 1) & (df_resultados5['Contacto_Identificado_Humano'].fillna(0) == 1), 1, 0)
    df_resultados5['Venta_Humano_Identificado'] = np.where((df_resultados5['Venta_Humano'].fillna(0) == 1), 1, 0)
    
    # Clasificar grupo de operador
    df_resultados5['Grupo_Operador'] = np.where(
        df_resultados5['Operado_Por__c'].isin(['DIGITAL_2', 'DIGITAL_MONTOS_BAJOS', 'DIGITAL_1', 'DIGITAL_ESPECIAL']), "DIGITAL",
        np.where(df_resultados5['Operado_Por__c'].isin(['QNT_RBK_2', 'QNT_RBK_1.2', 'QNT_RBK_1.1']), "RBK",
        np.where(df_resultados5['Operado_Por__c'].isin(['QNT_RECAUDO', 'QNT_PERSONA_JURIDICA', 'QNT_JUD']), "MONTOS_ALTOS",
        np.where(df_resultados5['Operado_Por__c'].isin(['GENNIALS_BPO_2', 'GENNIALS_BPO', 'HELLO_BPO', 'MAPNOVA', 'ESTA_BIEN_GROUP', 'QNT_COBRO']), "SATELITES",
        np.where(df_resultados5['Operado_Por__c'].str.contains('MANT'), "MANTENIMIENTO", "OTRO")))))
    
    # Exportar a BigQuery
    df_resultados5['DATE'] = pd.to_datetime(df_resultados5['DATE'])
    
    df_resultados5[["Fecha_dia", 'DATE', 'TELEPHONE', 'COD_ACT', 'Grupo_Operador', 'Operado_Por__c', 'CONN_ID', 'Contacto__c', 
                    'Contacto_Identificado_Robot', 'Gestion_Humano', 'Contacto_Identificado_Humano', 'Venta_Humano_Identificado']].to_gbq(
        'Operacion_Analitica.Embudo_Positivo_Robot', if_exists='append', credentials=credentials, project_id=project_id)
    
    # Actualizar tabla mensual
    df_resultados6 = df_resultados5[['Grupo_Operador', 'Operado_Por__c', 'Contacto__c']].drop_duplicates()
    df_resultados6['Mes'] = dia_actual[0:7]
    
    list_clientes = df_resultados5[df_resultados5['Contacto_Identificado_Robot'] == 1]['Contacto__c'].unique()
    df_resultados6['Contacto_Identificado_Robot'] = np.where(df_resultados6['Contacto__c'].isin(list_clientes), 1, 0)
    
    # Gestiones posteriores al bot
    df_gestion_posterior_bot = pd.merge(df_resultados5, df_gestion, on='Contacto__c')
    list_clientes_gestion = df_gestion_posterior_bot[df_gestion_posterior_bot['Fecha_dia_y'] > df_gestion_posterior_bot['Fecha_dia_x']]['Contacto__c'].unique()
    df_resultados6['Gestion_Humano'] = np.where((df_resultados6['Contacto__c'].isin(list_clientes_gestion)) & (df_resultados6['Contacto_Identificado_Robot'] == 1), 1, 0)
    
    df_contacto_posterior_bot = pd.merge(df_resultados5, df_contacto, on='Contacto__c')
    list_clientes_contacto = df_contacto_posterior_bot[df_contacto_posterior_bot['Fecha_dia_y'] > df_contacto_posterior_bot['Fecha_dia_x']]['Contacto__c'].unique()
    df_resultados6['Contacto_Identificado_Humano'] = np.where((df_resultados6['Contacto__c'].isin(list_clientes_contacto)) & (df_resultados6['Gestion_Humano'] == 1), 1, 0)
    
    df_resultados6.to_gbq('Operacion_Analitica.Embudo_Positivo_Robot_Mensual', if_exists='append', credentials=credentials, project_id=project_id)
    
    # Actualizar tablas finales
    query = f"""
    CREATE OR REPLACE TABLE Operacion_Analitica.Embudo_Positivo_Robot_Mensual AS
        SELECT Grupo_Operador, Operado_Por__c, Contacto__c, SUBSTR(Fecha_dia, 1,7) Mes, MAX(Contacto_Identificado_Robot) Contacto_Identificado_Robot, MAX(Gestion_Marcador) Gestion_Marcador,
        MAX(Gestion_Humano) Gestion_Humano, MAX(Contacto_Identificado_Humano) Contacto_Identificado_Humano
        FROM Operacion_Analitica.Embudo_Positivo_Robot
        GROUP BY Grupo_Operador, Operado_Por__c, Contacto__c, Mes
    """
    query_job = client.query(query)
    results = query_job.result()
    
    query = f"""
    CREATE OR REPLACE TABLE Operacion_Analitica.Embudo_Positivo_Robot AS
    SELECT DISTINCT
        TAB1.*EXCEPT(Ultimo_Contacto, Entidad_principal, localizado_historico, Gestion_Marcador),
        TAB2.Fecha_Gestion__c AS Ultimo_Contacto, TAB3.Entidad_principal,
        CASE WHEN DATE_DIFF(DATE(DATE), DATE(Fecha_Gestion__c), MONTH) <= 6 THEN "LOCALIZADO"
             WHEN Fecha_Gestion__c IS NOT NULL THEN "PERDIDO"
             ELSE "NO_LOCALIZADO" END AS localizado_historico,
        CASE WHEN TAB4.FechaMod IS NOT NULL AND Contacto_Identificado_Robot = 1 THEN 1 ELSE 0 END AS Gestion_Marcador
    FROM `Operacion_Analitica.Embudo_Positivo_Robot` TAB1
    LEFT JOIN (
        SELECT Contacto__c, Fecha_Gestion__c
        FROM `Operacion_Analitica.GestionesTitular`
    ) TAB2 ON TAB1.Contacto__c = TAB2.Contacto__c AND DATE(TAB2.Fecha_Gestion__c) < DATE(TAB1.Fecha_dia)
    LEFT JOIN `Campanas.Campanas_intradia` TAB3 ON TAB1.Contacto__c = TAB3.Contacto__c
    LEFT JOIN `SalesForce.Campanas_Marcador` TAB4 ON TAB4.Info1 = TAB1.Contacto__c AND SUBSTR(CAST(TAB4.FechaMod AS STRING), 1, 10) = TAB1.Fecha_dia
    QUALIFY ROW_NUMBER() OVER(PARTITION BY TAB1.CONN_ID ORDER BY TAB2.Fecha_Gestion__c DESC) = 1
    """
    query_job = client.query(query)
    results = query_job.result()
    
    # Exportar resultados del día
    for i in df_resultados5['Grupo_Operador'].unique():
        df_temp_i = df_resultados5[df_resultados5['Grupo_Operador'] == i]
        df_temp_i.to_excel(path + f"POSITIVOS ROBOT {i} RESULTADOS DÍA {dia_actualizacion[0]}.xlsx", index=False)
    
    _log("✅ EMBUDO COMPLETADO EXITOSAMENTE")
    return df_resultados5

# ===========================================================================
# EJECUCIÓN
# ===========================================================================

if __name__ == "__main__":
    dia_actualizacion = ["2026-08-12"]
    df_resultados = ejecutar_embudo(dia_actualizacion)
    print(f"Total registros procesados: {len(df_resultados)}")
    print(f"Ventas del día: {df_resultados['Venta_Humano_Identificado'].sum()}")